import {StyleSheet} from 'react-native';
import {COLOR, FONTSIZE, FONT_FAMILY, WIDTH} from '../../base/core';
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    height: WIDTH * 92,
    width: WIDTH * 428,
    backgroundColor: '#0E448A',
    paddingHorizontal: WIDTH * 18,
    justifyContent: 'space-between',
    paddingTop: WIDTH * 50,
  },
  header_right: {
    flexDirection: 'row',
  },
  iconBell: {
    width: WIDTH * 27,
    height: WIDTH * 27,
    tintColor: '#FFF',
  },
  iconBack: {
    width: WIDTH * 27,
    height: WIDTH * 27,
    tintColor: '#FFF',
  },
  iconMore: {
    width: WIDTH * 27,
    height: WIDTH * 27,
    tintColor: '#FFF',
    marginLeft: WIDTH * 23,
  },
  number: {
    backgroundColor: '#EF7749',
    width: WIDTH * 17,
    height: WIDTH * 17,
    color: '#fff',
    paddingLeft: WIDTH * 5,
    fontSize: 10,
    borderRadius: 20,
    position: 'absolute',
    right: 44,
    top: -3,
  },
  switch: {
    marginTop: WIDTH * 20,
    marginBottom: WIDTH * 17,
    flexDirection: 'row',
    width: WIDTH * 296,
    height: WIDTH * 31,
    backgroundColor: '#E8E7E7',
    borderRadius: WIDTH * 27,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: WIDTH * 66,
  },
  payment: {
    color: '#fff',
    fontSize: FONTSIZE.f_12,
    fontFamily: FONT_FAMILY.bold,
    backgroundColor: '#45B9A4',
    width: WIDTH * 148,
    height: WIDTH * 31,
    borderRadius: WIDTH * 27,
    paddingHorizontal: WIDTH * 42,
    paddingVertical: WIDTH * 7,
  },
  change: {
    color: '#fff',
    fontSize: FONTSIZE.f_12,
    fontFamily: FONT_FAMILY.bold,
    backgroundColor: '#ED5B54',
    width: WIDTH * 148,
    height: WIDTH * 31,
    borderRadius: WIDTH * 27,
    paddingHorizontal: WIDTH * 34,
    paddingVertical: WIDTH * 7,
  },
  body: {
    paddingHorizontal: WIDTH * 18,
  },
  title: {
    color: '#7A7A7A',
    fontSize: FONTSIZE.f_12,
    fontFamily: FONT_FAMILY.regular,
    marginBottom: WIDTH * 5,
  },
  choose: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: WIDTH * 10,
    borderWidth: WIDTH * 1,
    paddingVertical: WIDTH * 10,
    justifyContent: 'space-between',
    paddingLeft: WIDTH * 4,
    paddingRight: WIDTH * 16,
    marginBottom: WIDTH * 12,
  },

  iconDropdown: {
    width: WIDTH * 12,
    height: WIDTH * 7,
  },
  iconCopy: {
    width: WIDTH * 23,
    height: WIDTH * 23,
    resizeMode: 'contain',
  },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: WIDTH * 10,
    borderWidth: WIDTH * 1,
    height: WIDTH *45,
    justifyContent: 'space-between',
    paddingLeft: WIDTH * 4,
    paddingRight: WIDTH * 16,
    marginBottom: WIDTH * 12,
  },
});
export default styles;
