import {StyleSheet} from 'react-native';
import {
  COLOR,
  FONTSIZE,
  FONT_FAMILY,
  WIDTH,
  WIDTH_WINDOW,
} from '../../../base/core';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: WIDTH_WINDOW,
    paddingBottom: WIDTH * 120,
  },
  iconDropUp: {
    width: WIDTH * 12,
    height: WIDTH * 7,
    resizeMode: 'contain',
  },
  viewDrop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 0.9,
    backgroundColor: '#E8E7E7',
    paddingHorizontal: WIDTH * 8,
    paddingVertical: WIDTH * 8,
    borderRadius: WIDTH * 51,
  },
  info: {
    flex: 1,
    textAlign: 'right',
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_12,
    color: COLOR.BLACK_P,
  },
  viewHead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
    marginTop: WIDTH * 10,
    marginBottom: WIDTH * 14,
  },
  viewInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
  },
  infoCode: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.8,
  },
  btnSearchCode: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#E8E7E7',
    paddingVertical: WIDTH * 6,
    borderRadius: WIDTH * 51,
    paddingHorizontal: WIDTH * 16,
    marginRight: WIDTH * 24,
    flex: 0.8,
  },
  btnPriceCode: {
    backgroundColor: '#E8E7E7',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: WIDTH * 6,
    borderRadius: WIDTH * 51,
    flex: 1,
  },
  iconInfo: {
    width: WIDTH * 12,
    height: WIDTH * 12,
    resizeMode: 'contain',
    marginLeft: WIDTH * 4,
  },
  iconSearch: {
    width: WIDTH * 16,
    height: WIDTH * 16,
    resizeMode: 'contain',
  },
  price: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_15,
    color: '#737373',
  },
  textCode: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_15,
    color: '#404040',
  },
  viewFloor: {
    backgroundColor: COLOR.WHITE_P,
    borderRadius: WIDTH * 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: WIDTH * 4,
    marginTop: WIDTH * 8,
  },
  containerInfoPrice: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
  },
  priceBuy: {
    backgroundColor: COLOR.WHITE_P,
    borderRadius: WIDTH * 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: WIDTH * 4,
    marginTop: WIDTH * 8,
  },
  txtPrice: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_10,
  },
  viewInfoPriceFirst: {
    flex: 0.45,
    marginRight: WIDTH * 8,
  },
  viewInfoPriceSecond: {
    flex: 1.2,
  },
  viewDecrement: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#E8E7E7',
    borderRadius: WIDTH * 41,
  },
  containerPurchase: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
    justifyContent: 'space-between',
    marginTop: WIDTH * 20,
    marginBottom: WIDTH * 10,
  },
  plus: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_15,
    color: '#404040',
    flex: 1,
    textAlign: 'center',
  },
  icon: {
    width: WIDTH * 13,
    height: WIDTH * 13,
    resizeMode: 'contain',
  },
  btnPlus: {
    padding: WIDTH * 14,
  },
  containerlimit: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLOR.WHITE_P,
    paddingHorizontal: WIDTH * 16,
    paddingVertical: WIDTH * 13,
  },
  viewLimit: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: WIDTH * 26,
  },
  containerAllMoney: {
    paddingHorizontal: WIDTH * 16,
    paddingTop: WIDTH * 10,
  },
  line: {
    height: 2,
    backgroundColor: '#E8E7E7',
    marginBottom: WIDTH * 8,
  },
  sumAll: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: WIDTH * 11,
  },
  viewSumMoney: {
    backgroundColor: '#E8E7E7',
    paddingVertical: WIDTH * 8,
    paddingHorizontal: WIDTH * 69,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: WIDTH * 41,
  },
  contaierOrder: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: WIDTH * 11,
  },
  viewOrder: {
    backgroundColor: COLOR.WHITE_P,
    borderRadius: WIDTH * 50,
    paddingHorizontal: WIDTH * 9,
    paddingVertical: WIDTH * 4,
  },
  txtOrder: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_12,
    color: '#404040',
  },
  containerLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
    paddingVertical: WIDTH * 4,
  },
  containerLabelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WIDTH * 16,
    paddingVertical: WIDTH * 4,
  },
  label: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: FONTSIZE.f_12,
    color: '#404040',
    flex: 1,
    textAlign: 'center',
  },
  foot: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    bottom: WIDTH * 75,
    paddingHorizontal: WIDTH * 16,
  },
  btnPurchase: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: WIDTH * 7,
    borderRadius: WIDTH * 74,
  },
});
export default styles;
