const en = {
  home: 'Home',
  priceList: ' List Price',
  property: 'Property',
  purchase: 'Purchase',
  chat: 'Chat',
  infoUser: 'Info user',
  setting: 'Setting',
  changePassword: 'Change Password',
  loginWithFace: 'Login with Face/ Touch ID',
  logOut: 'Logout',
  wealthPlan: 'ACCUMULATION PLAN',
  assetsForChildren: 'ASSETS FOR CHILDREN',
  retirement_Assets: 'RETIREMENT ASSETS',
  SavingToBuyACarAndAHouse: 'SAVING TO BUY CAR/HOUSE',
  targetAmount: 'Target amount',
  startingAge: 'Starting age',
  endAge: 'End age',
  initialAmount: 'Initial amount',
  inflationary_Year: 'Inflationary/Year',
  actualAmountToAccumulate: 'Actual amount to accumulate',
  d_year: 'đ/year',
  percent_year: '%/year',
  d_month: 'đ/month',
  SpendingInRetirement_Month: 'Spending inRetirement month',
  CurrentAge: 'Current age',
  RetiredAge: 'Retired age',
  Setup: 'SET UP',
  openAccount: 'OPEN ACCOUNT',
  phoneNumber: 'Phone number',
  identificationCard: 'Identification card',
  fullName: 'Full name',
  dateOfBirth: 'Date of birth',
  permanentAddress: 'Permanent address',
  contactAddress: 'Contact address',
  gender: 'Gender',
  dateOfIssue: 'Date of issue',
  placeOfIssue: 'Place of issue',
  faceAuthentication: 'Face authentication',
  success: 'Success',
  registerService: 'REGISTER SERVICE',
  SignUpForMarginTradingService: 'Sign up for margin trading service',
  informationOfBankIsAccount: 'INFORMATION OF BANK IS ACCOUNT',
  bank: 'Bank',
  branch: 'Branch',
  bankAccountNumber: 'Bank account number',
  broker: 'BROKER',
  brokerCode: 'Broker code',
  brokerName: 'Broker name',
  collaborators: 'COLLABORATORS',
  collaboratorCode: 'Collaborator code',
  collaboratorIsName: 'Collaborator is name',
  referralInformationoptional: 'REFERRALINFORMATION (OPTIONAL)',
  referralCode: 'Referral code',
  referrerIsName: 'Referrer is name',
  rules:
    'I hereby undertake to be responsible for all the information declared and verified receive the registration to open a securities trading account.',
  detail: 'Contract details',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  registration: 'REGISTRATION',
<<<<<<< HEAD
  accountList: ' Account list',
  customerName: ' Customer name',
  referrerName: 'Referrer name',
  depositoryNumber: ' Depository number ',
  identityCardNumber: 'Identity Card Number',
  email: ' Email ',
  phoneNumber: ' Phone Number',
  address: ' Address',
  language: 'Language',
  notification: 'Notification',
  command: 'Command',
  account: ' Account',
  news: 'News',
  payment: ' Payment',
  transfers: ' Transfers',
  paymentAccount: 'Payment Account',
  chooseBeneficiaryBank: ' Choose beneficiary bank',
  beneficiaryName: ' Beneficiary name',
  transferContents: 'Transfer Contents',
  transactionType: 'Transaction type',
  fromAccount: 'From the Account',
  toAccount: 'To the Account',
  content: 'Content',
  password: 'Password',
=======
  stopAccumulating: 'Stop\naccumulate',
  considerSelling: 'Consider\nselling',
  codeCK: 'Code Ck',
  matching:'Matching',
  flexibleInvestment: 'FLEXIBLE INVESTMENT',
  alls:'ALL',


>>>>>>> c1c65c1ebe3cce1e973b347e06040d19ff6df230
};
export default en;
