const vi = {
  home: 'Trang chủ',
  priceList: 'Bảng giá',
  property: 'Tích sản',
  purchase: 'Giao dịch',
  chat: 'Chat',
  infoUser: 'Thông tin cá nhân',
  setting: 'Cài đặt',
  changePassword: 'Đổi mật khẩu',
  loginWithFace: 'Đăng nhập bằng Face/ TouchId',
  logOut: 'Đăng xuất',
  wealthPlan: 'KẾ HOẠCH TÍCH SẢN',
  assetsForChildren: 'TÍCH SẢN CHO CON',
  retirement_Assets: 'TÍCH SẢN CHO HƯU TRÍ',
  SavingToBuyACarAndAHouse: 'TÍCH SẢN MUA NHÀ/OTO',
  targetAmount: 'số tiền mục tiêu',
  startingAge: 'Tuổi bắt đầu',
  endAge: 'Tuổi kết thúc',
  initialAmount: 'Số tiền ban đầu',
  inflationary_Year: 'Lạm phát/năm',
  actualAmountToAccumulate: 'Số tiền thực tế cần tích sản',
  d_year: 'đ/năm',
  percent_year: '%/năm',
  d_month: 'đ/tháng',
  SpendingInRetirement_Month: 'Chi tiêu khi nghỉ hưu/tháng',
  CurrentAge: 'Tuổi hiện tại',
  RetiredAge: 'Tuổi nghỉ hưu',
  Setup: 'THIẾT LẬP',
  openAccount: 'MỞ TÀI KHOẢN',
  phoneNumber: 'Số điện thoại',
  identificationCard: 'Số CMND/CCCD',
  fullName: 'Họ và tên',
  dateOfBirth: 'Ngày sinh',
  permanentAddress: 'Địa chỉ thường trú',
  contactAddress: 'Địa chỉ liên lạc',
  gender: 'Giới tính',
  dateOfIssue: 'Ngày cấp',
  placeOfIssue: 'Nơi cấp',
  faceAuthentication: 'Xác thực khuôn mặt',
  success: 'Thành công',
  registerService: 'ĐĂNG KÝ DỊCH VỤ',
  SignUpForMarginTradingService: 'Đăng ký dịch vụ giao dịch ký quỹ',
  informationOfBankIsAccount: 'THÔNG TIN TÀI KHOẢN NGÂN HÀNG',
  bank: 'Ngân hàng',
  branch: 'Chi nhánh',
  bankAccountNumber: 'Số tài khoản ngân hàng',
  broker: 'NHÂN VIÊN MÔI GIỚI',
  brokerCode: 'Mã nhân viên môi giới',
  brokerName: 'Tên nhân viên môi giói',
  collaborators: 'CỘNG TÁC VIÊN',
  collaboratorCode: 'Mã nhân viên môi giới',
  collaboratorIsName: 'Tên nhân viên môi giới',
  referralInformationoptional: 'THÔNG TIN NGƯỜI GIỚI THIỆU (TÙY CHỌN)',
  referralCode: 'Mã người giới thiệu',
  referrerIsName: 'Tên người giới thiệu',
  rules:
    ' Tôi xin cam kết chịu trách nhiệm về mọi thông tin đã khai báo và xác nhận việc đăng ký mở tài khoản giao dịch chứng khoán.',
  detail: 'Chi tiết hợp đồng',
  male: 'Nam',
  female: 'Nữ',
  other: 'Khác',
  registration: 'ĐĂNG KÝ',
  stopAccumulating:'Ngừng\ntích sản',
  considerSelling:' Cân\nnhắc bán',
  codeCK: 'Mã Ck',
  matching:'Khớp',
  flexibleInvestment:'ĐẦU TƯ NĂNG ĐỘNG',
  alls:'TỔNG TÀI SẢN'


};
export default vi;
